<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/07/06 15:40:06

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=termswatch;host=localhost',
  'username' => 'termswatch',
  'password' => 'termswatch',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
