<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/07/06 15:40:06
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'timeline',
  'action' => 'timeline',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
