<?php


/**
 * This class adds structure of 'policy' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Aug  4 13:49:17 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PolicyMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PolicyMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(PolicyPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(PolicyPeer::TABLE_NAME);
		$tMap->setPhpName('Policy');
		$tMap->setClassname('Policy');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('PID', 'Pid', 'INTEGER', true, null);

		$tMap->addForeignKey('CID', 'Cid', 'INTEGER', 'company', 'CID', true, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', true, 255);

		$tMap->addColumn('URL', 'Url', 'VARCHAR', true, 255);

		$tMap->addColumn('SCRAPEMETHOD', 'Scrapemethod', 'TINYINT', true, null);

		$tMap->addColumn('SCRAPEDATA', 'Scrapedata', 'LONGVARCHAR', true, null);

		$tMap->addColumn('SPOOF', 'Spoof', 'VARCHAR', false, 255);

		$tMap->addColumn('PRE', 'Pre', 'TINYINT', true, null);

	} // doBuild()

} // PolicyMapBuilder
